services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
